### ISSUE TITLE
Handle timeout of response.read() in bullyblinder

### ISSUE THREAD

**Issue by hadojae** [hadojae/DATA#10]
> Traceback (most recent call last):
  File "/home/$USER/bullyblinder.py", line 1107, in <module>
    page = response.read()
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_response.py", line 190, in read
    self.__cache.write(self.wrapped.read())
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 588, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 648, in _read_chunked
    value.append(self._safe_read(amt))
  File "/usr/lib/python2.7/httplib.py", line 703, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.timeout: timed out

**Comment by hadojae** [comment]
https://github.com/hadojae/DATA/commit/84a64a2ae1fac4ad3e45f15bf814ada5d5efe996
