### ISSUE TITLE
Mechanize error when viewing unknown document

### ISSUE THREAD

**Issue by hadojae** [hadojae/DATA#5]
> Capturing on 'eth0'
Traceback (most recent call last):
  File "/home/$user/bullyblinder.py", line 1110, in <module>
    if br.geturl().startswith("http"): 
  File "build/bdist.linux-x86_64/egg/mechanize/_mechanize.py", line 334, in geturl
mechanize._mechanize.BrowserStateError: not viewing any document

> Capturing on 'eth0'
Traceback (most recent call last):
  File "/home/$user/bullyblinder.py", line 1136, in <module>
    response = redirs_and_obfuscations(page, current_url)
  File "/home/$user/bullyblinder.py", line 429, in redirs_and_obfuscations
    elif br.title() and 'ameli.fr' in br.title():
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 459, in title
    raise BrowserStateError("not viewing HTML")
mechanize._mechanize.BrowserStateError: not viewing HTML

**Comment by hadojae** [comment]
Fixed
